services:
  test:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    command: ["pytest"]
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend

networks:
  backend:

volumes:
  redis-data:
